import { defineScene } from "../schema";

export const hybridSessionsScene = defineScene({
  meta: {
    id: "hybrid-sessions",
    title: "Hybrid Sessions",
    description:
      "Ephemeral sandboxes spin up for intermittent work, save history and filesystem state, and can resume later with stored context.",
    durationMs: 11200,
    viewport: { width: 1200, height: 550, padding: 40 },
  },
  nodes: [
    { id: "user-source", kind: "source", x: 190, y: 160, width: 244, height: 96, label: "User Input", subtitle: "Prompt or task", icon: "user" },
    { id: "api-source", kind: "source", x: 190, y: 380, width: 244, height: 96, label: "System Events", subtitle: "Automated triggers", icon: "webhook" },
    { id: "control-plane", kind: "service", x: 490, y: 270, width: 232, height: 112, label: "Control Plane", subtitle: "Routes work", icon: "controlPlane" },
    { id: "session-store", kind: "db", x: 1025, y: 270, width: 248, height: 104, label: "Session State", subtitle: "History + filesystem", icon: "database" },
    {
      id: "sandbox-a",
      kind: "sandbox",
      x: 745,
      y: 160,
      width: 232,
      height: 112,
      label: "Sandbox A",
      icon: "agent",
      fill: "#edf3ff",
      stroke: "#4667b4",
      accent: "#6f8fe1",
    },
    { id: "sandbox-b", kind: "sandbox", x: 745, y: 380, width: 232, height: 112, label: "Sandbox B", icon: "agent" },
    { id: "control-plane-core", kind: "service", x: 490, y: 270, width: 2, height: 2, label: "Control Plane Core", hidden: true },
    { id: "sandbox-a-core", kind: "sandbox", x: 745, y: 160, width: 2, height: 2, label: "Sandbox A Core", hidden: true },
    { id: "sandbox-b-core", kind: "sandbox", x: 745, y: 380, width: 2, height: 2, label: "Sandbox B Core", hidden: true },
    { id: "session-store-core", kind: "db", x: 1025, y: 270, width: 2, height: 2, label: "Session Store Core", hidden: true },
  ],
  edges: [
    { id: "user-to-control", from: "user-source", to: "control-plane-core", route: "smooth" },
    { id: "api-to-control", from: "api-source", to: "control-plane-core", route: "smooth" },
    { id: "control-to-a", from: "control-plane", to: "sandbox-a-core", route: "smooth" },
    { id: "control-to-b", from: "control-plane", to: "sandbox-b-core", route: "smooth" },
    { id: "state-to-a", from: "session-store", to: "sandbox-a-core", route: "smooth" },
    { id: "state-to-b", from: "session-store", to: "sandbox-b-core", route: "smooth" },
    { id: "a-to-state", from: "sandbox-a", to: "session-store-core", route: "smooth" },
    { id: "b-to-state", from: "sandbox-b", to: "session-store-core", route: "smooth" },
  ],
  events: [
    { id: "task-1", edgeId: "user-to-control", startMs: 0, durationMs: 760, style: "message", status: "ok" },
    { id: "spawn-a", edgeId: "control-to-a", startMs: 1160, durationMs: 560, style: "message", status: "ok" },
    { id: "hydrate-a-state", edgeId: "state-to-a", startMs: 1320, durationMs: 760, style: "stream", status: "ok" },
    { id: "save-a-state", edgeId: "a-to-state", startMs: 4620, durationMs: 760, style: "message", status: "ok" },
    { id: "task-2", edgeId: "api-to-control", startMs: 5660, durationMs: 780, style: "message", status: "ok" },
    { id: "resume-b", edgeId: "control-to-b", startMs: 6800, durationMs: 560, style: "message", status: "ok" },
    { id: "hydrate-b-state", edgeId: "state-to-b", startMs: 7000, durationMs: 760, style: "stream", status: "ok" },
    { id: "save-b-state", edgeId: "b-to-state", startMs: 10180, durationMs: 760, style: "message", status: "ok" },
  ],
  effects: [
    { id: "control-intake-user", kind: "edgeEmphasis", edgeId: "user-to-control", startMs: 0, endMs: 920, intensity: 0.8 },
    { id: "control-intake-api", kind: "edgeEmphasis", edgeId: "api-to-control", startMs: 5660, endMs: 6520, intensity: 0.8 },
    { id: "control-pulse-a", kind: "nodePulse", nodeId: "control-plane", startMs: 620, endMs: 1320, intensity: 0.55 },
    { id: "control-pulse-b", kind: "nodePulse", nodeId: "control-plane", startMs: 6260, endMs: 7000, intensity: 0.55 },
    { id: "sandbox-a-presence", kind: "nodePresence", nodeId: "sandbox-a", startMs: 980, endMs: 5480, intensity: 0.95 },
    { id: "sandbox-a-status-initializing", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Initializing", startMs: 980, endMs: 1640, intensity: 1 },
    { id: "sandbox-a-status-hydrating", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Hydrating", startMs: 1640, endMs: 2140, intensity: 1 },
    { id: "sandbox-a-status-processing", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Processing", startMs: 2140, endMs: 4320, intensity: 1 },
    { id: "sandbox-a-status-complete", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Complete", startMs: 4320, endMs: 4700, intensity: 1 },
    { id: "sandbox-a-status-snapshotting", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Snapshotting", startMs: 4700, endMs: 5480, intensity: 1 },
    { id: "sandbox-a-progress", kind: "nodeProgress", nodeId: "sandbox-a", startMs: 2140, endMs: 4320, intensity: 1 },
    { id: "sandbox-b-presence", kind: "nodePresence", nodeId: "sandbox-b", startMs: 6620, endMs: 11020, intensity: 0.95 },
    { id: "sandbox-b-status-initializing", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Initializing", startMs: 6620, endMs: 7320, intensity: 1 },
    { id: "sandbox-b-status-hydrating", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Hydrating", startMs: 7320, endMs: 7900, intensity: 1 },
    { id: "sandbox-b-status-processing", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Processing", startMs: 7900, endMs: 9960, intensity: 1 },
    { id: "sandbox-b-status-complete", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Complete", startMs: 9960, endMs: 10260, intensity: 1 },
    { id: "sandbox-b-status-snapshotting", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Snapshotting", startMs: 10260, endMs: 11020, intensity: 1 },
    { id: "sandbox-b-progress", kind: "nodeProgress", nodeId: "sandbox-b", startMs: 7900, endMs: 9960, intensity: 1 },
    { id: "storage-pulse-a-hydrate", kind: "nodePulse", nodeId: "session-store", startMs: 1360, endMs: 2140, intensity: 0.5 },
    { id: "storage-pulse-a-save", kind: "nodePulse", nodeId: "session-store", startMs: 4700, endMs: 5480, intensity: 0.5 },
    { id: "storage-pulse-b-hydrate", kind: "nodePulse", nodeId: "session-store", startMs: 7040, endMs: 7820, intensity: 0.5 },
    { id: "storage-pulse-b-save", kind: "nodePulse", nodeId: "session-store", startMs: 10260, endMs: 11020, intensity: 0.5 },
  ],
});
