import { defineScene } from "../schema";

export const insideVsOutsideSandboxScene = defineScene({
  meta: {
    id: "inside-vs-outside-sandbox",
    title: "Agent Inside vs Outside Sandbox",
    description:
      "Compare how boundary crossings change latency, response time, and visible task progress when the coding agent runs inside or outside the sandbox.",
    durationMs: 12000,
    viewport: { width: 1280, height: 720, padding: 56 },
  },
  controls: [
    { key: "sandboxBoundaryLatencyMs", label: "Sandbox boundary", min: 20, max: 500, step: 10, defaultValue: 160, unit: "ms" },
    { key: "modelApiLatencyMs", label: "Model API latency", min: 20, max: 500, step: 10, defaultValue: 120, unit: "ms" },
    { key: "modelResponseMs", label: "Model response", min: 300, max: 4000, step: 100, defaultValue: 1400, unit: "ms" },
    { key: "toolExecutionMs", label: "Tool execution", min: 100, max: 2000, step: 50, defaultValue: 650, unit: "ms" },
    {
      key: "taskDifficulty",
      label: "Task difficulty",
      min: 0,
      max: 3,
      step: 1,
      defaultValue: 30,
      options: [
        { label: "Easy (10 tool calls)", value: 10 },
        { label: "Medium (30 tool calls)", value: 30 },
        { label: "Difficult (70 tool calls)", value: 70 },
        { label: "Very difficult (200 tool calls)", value: 200 },
      ],
    },
    { key: "playbackSpeed", label: "Playback speed", min: 0.5, max: 4, step: 0.5, defaultValue: 1, unit: "x" },
  ],
  zones: [
    { id: "outside-sandbox-zone", label: "Sandbox boundary", x: 100, y: 330, width: 410, height: 185, style: "sandbox" },
    { id: "inside-sandbox-zone", label: "Sandbox boundary", x: 770, y: 140, width: 360, height: 380, style: "external" },
  ],
  metrics: [
    { id: "outsideTotal", label: "Outside total", x: 74, y: 76, tone: "warning" },
    { id: "insideTotal", label: "Inside total", x: 74, y: 142, tone: "positive" },
    { id: "boundaryPenalty", label: "Boundary cost", x: 74, y: 540, tone: "warning" },
    { id: "modelLoop", label: "Model loop", x: 74, y: 606, tone: "positive" },
  ],
  simulation: {
    kind: "insideOutsideComparison",
    outsideNodeId: "outside-agent",
    insideNodeId: "inside-agent",
    outsideModelNodeId: "model-api",
    insideModelNodeId: "model-api",
    outsideEntryEdgeId: "outside-agent-to-model",
    insideEntryEdgeId: "inside-agent-to-model",
    outsideModelCallEdgeId: "outside-agent-to-model",
    outsideModelResultEdgeId: "model-to-outside-agent",
    insideModelCallEdgeId: "inside-agent-to-model",
    insideModelResultEdgeId: "model-to-inside-agent",
    outsideToolCallEdgeId: "outside-agent-to-tools",
    outsideToolResultEdgeId: "outside-tools-to-agent",
    insideToolCallEdgeId: "inside-agent-to-tools",
    insideToolResultEdgeId: "inside-tools-to-agent",
  },
  nodes: [
    { id: "model-api", kind: "service", x: 620, y: 250, width: 250, height: 110, label: "Model Provider API", subtitle: "" },
    {
      id: "outside-agent",
      kind: "sandbox",
      x: 300,
      y: 250,
      width: 282,
      height: 122,
      label: "Agent (Outside Sandbox)",
      fill: "#f6efe7",
      stroke: "#8a6745",
      accent: "#c39b6c",
      showProgress: false,
    },
    {
      id: "inside-agent",
      kind: "sandbox",
      x: 940,
      y: 250,
      width: 282,
      height: 122,
      label: "Agent (Inside Sandbox)",
      fill: "#eefbf3",
      stroke: "#3f7d5e",
      accent: "#61b184",
      showProgress: false,
    },
    { id: "outside-tools", kind: "service", x: 300, y: 425, width: 168, height: 110, label: "Tools + FS", subtitle: "" },
    { id: "inside-tools", kind: "service", x: 940, y: 425, width: 188, height: 110, label: "Tools + FS", subtitle: "" }
  ],
  edges: [
    { id: "outside-agent-to-model", from: "outside-agent", to: "model-api", route: "straight" },
    { id: "model-to-outside-agent", from: "model-api", to: "outside-agent", route: "straight" },
    { id: "inside-agent-to-model", from: "inside-agent", to: "model-api", route: "straight" },
    { id: "model-to-inside-agent", from: "model-api", to: "inside-agent", route: "straight" },
    { id: "outside-agent-to-tools", from: "outside-agent", to: "outside-tools", route: "straight" },
    { id: "outside-tools-to-agent", from: "outside-tools", to: "outside-agent", route: "straight" },
    { id: "inside-agent-to-tools", from: "inside-agent", to: "inside-tools", route: "straight" },
    { id: "inside-tools-to-agent", from: "inside-tools", to: "inside-agent", route: "straight" },
  ],
  events: [],
  effects: [],
});
