import { defineScene } from "../schema";

export const longRunningSessionsScene = defineScene({
  meta: {
    id: "long-running-sessions",
    title: "Long-Running Sessions",
    description:
      "Persistent agent containers stay warm while blue and green workstreams from multiple sources route to matching sessions.",
    durationMs: 9800,
    viewport: { width: 1280, height: 720, padding: 56 },
  },
  nodes: [
    { id: "user-source", kind: "source", x: 230, y: 230, width: 244, height: 96, label: "User Input", subtitle: "Prompt or task", icon: "user" },
    { id: "api-source", kind: "source", x: 230, y: 450, width: 244, height: 96, label: "System Events", subtitle: "Automated triggers", icon: "webhook" },
    { id: "control-plane", kind: "service", x: 555, y: 340, width: 232, height: 112, label: "Control Plane", subtitle: "Routes work", icon: "controlPlane" },
    {
      id: "sandbox-a",
      kind: "sandbox",
      x: 885,
      y: 230,
      width: 232,
      height: 112,
      label: "Sandbox A",
      icon: "agent",
      fill: "#edf3ff",
      stroke: "#4667b4",
      accent: "#6f8fe1",
    },
    {
      id: "sandbox-b",
      kind: "sandbox",
      x: 885,
      y: 450,
      width: 232,
      height: 112,
      label: "Sandbox B",
      icon: "agent",
      fill: "#eefbf3",
      stroke: "#3f7d5e",
      accent: "#61b184",
    },
    { id: "control-plane-core", kind: "service", x: 555, y: 340, width: 2, height: 2, label: "Control Plane Core", hidden: true },
    { id: "sandbox-a-core", kind: "sandbox", x: 885, y: 230, width: 2, height: 2, label: "Sandbox A Core", hidden: true },
    { id: "sandbox-b-core", kind: "sandbox", x: 885, y: 450, width: 2, height: 2, label: "Sandbox B Core", hidden: true },
  ],
  edges: [
    { id: "user-to-control", from: "user-source", to: "control-plane-core", route: "smooth" },
    { id: "api-to-control", from: "api-source", to: "control-plane-core", route: "smooth" },
    { id: "control-to-a", from: "control-plane", to: "sandbox-a-core", route: "smooth" },
    { id: "control-to-b", from: "control-plane", to: "sandbox-b-core", route: "smooth" },
  ],
  events: [
    { id: "user-blue-1", edgeId: "user-to-control", startMs: 0, durationMs: 720, style: "message", status: "ok" },
    { id: "route-blue-1", edgeId: "control-to-a", startMs: 850, durationMs: 560, style: "message", status: "ok" },
    { id: "api-green-1", edgeId: "api-to-control", startMs: 1180, durationMs: 760, style: "stream", status: "ok" },
    { id: "route-green-1", edgeId: "control-to-b", startMs: 2060, durationMs: 560, style: "stream", status: "ok" },
    { id: "api-blue-2", edgeId: "api-to-control", startMs: 3050, durationMs: 760, style: "message", status: "ok" },
    { id: "route-blue-2", edgeId: "control-to-a", startMs: 3930, durationMs: 560, style: "message", status: "ok" },
    { id: "user-green-2", edgeId: "user-to-control", startMs: 5120, durationMs: 720, style: "stream", status: "ok" },
    { id: "route-green-2", edgeId: "control-to-b", startMs: 5980, durationMs: 560, style: "stream", status: "ok" },
    { id: "user-blue-3", edgeId: "user-to-control", startMs: 6980, durationMs: 700, style: "message", status: "ok" },
    { id: "route-blue-3", edgeId: "control-to-a", startMs: 7780, durationMs: 560, style: "message", status: "ok" },
    { id: "api-green-3", edgeId: "api-to-control", startMs: 7700, durationMs: 760, style: "stream", status: "ok" },
    { id: "route-green-3", edgeId: "control-to-b", startMs: 8580, durationMs: 560, style: "stream", status: "ok" },
  ],
  effects: [
    { id: "sandbox-a-status-waiting-base", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Waiting", startMs: 0, endMs: 9800, intensity: 1 },
    { id: "sandbox-b-status-waiting-base", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Waiting", startMs: 0, endMs: 9800, intensity: 1 },
    { id: "control-pulse-1", kind: "nodePulse", nodeId: "control-plane", startMs: 540, endMs: 1160, intensity: 0.55 },
    { id: "control-pulse-2", kind: "nodePulse", nodeId: "control-plane", startMs: 1720, endMs: 2380, intensity: 0.55 },
    { id: "control-pulse-3", kind: "nodePulse", nodeId: "control-plane", startMs: 3600, endMs: 4260, intensity: 0.55 },
    { id: "control-pulse-4", kind: "nodePulse", nodeId: "control-plane", startMs: 5660, endMs: 6320, intensity: 0.55 },
    { id: "control-pulse-5", kind: "nodePulse", nodeId: "control-plane", startMs: 7500, endMs: 8160, intensity: 0.55 },
    { id: "control-pulse-6", kind: "nodePulse", nodeId: "control-plane", startMs: 8360, endMs: 9100, intensity: 0.55 },
    { id: "sandbox-a-job-1", kind: "nodeProgress", nodeId: "sandbox-a", startMs: 1180, endMs: 2120, intensity: 1 },
    { id: "sandbox-a-status-processing-1", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Processing", startMs: 1180, endMs: 2120, intensity: 1 },
    { id: "sandbox-b-job-1", kind: "nodeProgress", nodeId: "sandbox-b", startMs: 2360, endMs: 3320, intensity: 1 },
    { id: "sandbox-b-status-processing-1", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Processing", startMs: 2360, endMs: 3320, intensity: 1 },
    { id: "sandbox-a-job-2", kind: "nodeProgress", nodeId: "sandbox-a", startMs: 4260, endMs: 5200, intensity: 1 },
    { id: "sandbox-a-status-processing-2", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Processing", startMs: 4260, endMs: 5200, intensity: 1 },
    { id: "sandbox-b-job-2", kind: "nodeProgress", nodeId: "sandbox-b", startMs: 6320, endMs: 7220, intensity: 1 },
    { id: "sandbox-b-status-processing-2", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Processing", startMs: 6320, endMs: 7220, intensity: 1 },
    { id: "sandbox-a-job-3", kind: "nodeProgress", nodeId: "sandbox-a", startMs: 8100, endMs: 9000, intensity: 1 },
    { id: "sandbox-a-status-processing-3", kind: "nodeStatus", nodeId: "sandbox-a", statusLabel: "Processing", startMs: 8100, endMs: 9000, intensity: 1 },
    { id: "sandbox-b-job-3", kind: "nodeProgress", nodeId: "sandbox-b", startMs: 8920, endMs: 9640, intensity: 1 },
    { id: "sandbox-b-status-processing-3", kind: "nodeStatus", nodeId: "sandbox-b", statusLabel: "Processing", startMs: 8920, endMs: 9640, intensity: 1 },
    { id: "edge-user-active-1", kind: "edgeEmphasis", edgeId: "user-to-control", startMs: 0, endMs: 820, intensity: 0.8 },
    { id: "edge-api-active-1", kind: "edgeEmphasis", edgeId: "api-to-control", startMs: 1180, endMs: 2000, intensity: 0.8 },
    { id: "edge-api-active-2", kind: "edgeEmphasis", edgeId: "api-to-control", startMs: 3050, endMs: 3870, intensity: 0.8 },
    { id: "edge-user-active-2", kind: "edgeEmphasis", edgeId: "user-to-control", startMs: 5120, endMs: 5920, intensity: 0.8 },
    { id: "edge-user-active-3", kind: "edgeEmphasis", edgeId: "user-to-control", startMs: 6980, endMs: 7760, intensity: 0.8 },
    { id: "edge-api-active-3", kind: "edgeEmphasis", edgeId: "api-to-control", startMs: 7700, endMs: 8520, intensity: 0.8 },
  ],
});
