import { defineScene } from "../schema";

export const singleContainerScene = defineScene({
  meta: {
    id: "single-container",
    title: "Single Container",
    description:
      "A shared long-lived sandbox starts with one active agent and spawns additional agents inside the same container as workload increases.",
    durationMs: 10200,
    viewport: { width: 1280, height: 720, padding: 56 },
  },
  nodes: [
    { id: "user-source", kind: "source", x: 230, y: 230, width: 244, height: 96, label: "User Input", subtitle: "Prompt or task", icon: "user" },
    { id: "api-source", kind: "source", x: 230, y: 450, width: 244, height: 96, label: "System Events", subtitle: "Automated triggers", icon: "webhook" },
    { id: "control-plane", kind: "service", x: 555, y: 340, width: 232, height: 112, label: "Control Plane", subtitle: "Routes work", icon: "controlPlane" },
    {
      id: "global-sandbox",
      kind: "sandbox",
      x: 915,
      y: 340,
      width: 356,
      height: 276,
      label: "Global Sandbox",
      subtitle: "Shared environment",
      showProgress: false,
      fill: "#edf3ff",
      stroke: "#4667b4",
      accent: "#6f8fe1",
    },
    {
      id: "agent-1",
      kind: "service",
      x: 915,
      y: 335,
      width: 156,
      height: 80,
      label: "Agent 01",
      subtitle: "Spawned",
      icon: "agent",
      fill: "#edf3ff",
      stroke: "#4667b4",
      accent: "#6f8fe1",
    },
    {
      id: "agent-2",
      kind: "service",
      x: 827,
      y: 430,
      width: 156,
      height: 80,
      label: "Agent 02",
      subtitle: "Spawned",
      icon: "agent",
      fill: "#eefbf3",
      stroke: "#3f7d5e",
      accent: "#61b184",
    },
    {
      id: "agent-3",
      kind: "service",
      x: 1003,
      y: 430,
      width: 156,
      height: 80,
      label: "Agent 03",
      subtitle: "Spawned",
      icon: "agent",
      fill: "#f6efe7",
      stroke: "#8a6745",
      accent: "#c39b6c",
    },
    { id: "control-plane-core", kind: "service", x: 555, y: 340, width: 2, height: 2, label: "Control Plane Core", hidden: true },
    { id: "global-sandbox-core", kind: "sandbox", x: 915, y: 340, width: 2, height: 2, label: "Global Sandbox Core", hidden: true },
    { id: "agent-1-core", kind: "service", x: 915, y: 350, width: 2, height: 2, label: "Agent 01 Core", hidden: true },
    { id: "agent-2-core", kind: "service", x: 827, y: 430, width: 2, height: 2, label: "Agent 02 Core", hidden: true },
    { id: "agent-3-core", kind: "service", x: 1003, y: 430, width: 2, height: 2, label: "Agent 03 Core", hidden: true },
  ],
  edges: [
    { id: "user-to-control", from: "user-source", to: "control-plane-core", route: "smooth" },
    { id: "api-to-control", from: "api-source", to: "control-plane-core", route: "smooth" },
    { id: "control-to-sandbox", from: "control-plane", to: "global-sandbox-core", route: "smooth" },
    { id: "sandbox-to-agent-1", from: "global-sandbox", to: "agent-1-core", route: "smooth" },
    { id: "sandbox-to-agent-2", from: "global-sandbox", to: "agent-2-core", route: "smooth" },
    { id: "sandbox-to-agent-3", from: "global-sandbox", to: "agent-3-core", route: "smooth" },
  ],
  events: [
    { id: "user-burst-1", edgeId: "user-to-control", startMs: 0, durationMs: 720, style: "message", status: "ok" },
    { id: "route-burst-1", edgeId: "control-to-sandbox", startMs: 860, durationMs: 620, style: "message", status: "ok" },
    { id: "agent-1-work-1", edgeId: "sandbox-to-agent-1", startMs: 1520, durationMs: 540, style: "message", status: "ok" },
    { id: "api-burst-1", edgeId: "api-to-control", startMs: 1960, durationMs: 760, style: "stream", status: "ok" },
    { id: "route-burst-2", edgeId: "control-to-sandbox", startMs: 2840, durationMs: 620, style: "stream", status: "ok" },
    { id: "agent-2-work-1", edgeId: "sandbox-to-agent-2", startMs: 3480, durationMs: 540, style: "stream", status: "ok" },
    { id: "user-burst-2", edgeId: "user-to-control", startMs: 4460, durationMs: 720, style: "message", status: "ok" },
    { id: "route-burst-3", edgeId: "control-to-sandbox", startMs: 5320, durationMs: 620, style: "message", status: "ok" },
    { id: "agent-3-work-1", edgeId: "sandbox-to-agent-3", startMs: 5960, durationMs: 540, style: "warm", status: "ok" },
    { id: "api-burst-2", edgeId: "api-to-control", startMs: 6760, durationMs: 760, style: "stream", status: "ok" },
    { id: "route-burst-4", edgeId: "control-to-sandbox", startMs: 7640, durationMs: 620, style: "stream", status: "ok" },
    { id: "agent-2-work-2", edgeId: "sandbox-to-agent-2", startMs: 8280, durationMs: 540, style: "stream", status: "ok" },
    { id: "agent-1-work-2", edgeId: "sandbox-to-agent-1", startMs: 8580, durationMs: 540, style: "message", status: "ok" },
  ],
  effects: [
    { id: "sandbox-status-running", kind: "nodeStatus", nodeId: "global-sandbox", statusLabel: "Running", startMs: 0, endMs: 10200, intensity: 1 },
    { id: "sandbox-progress-1", kind: "nodeProgress", nodeId: "global-sandbox", startMs: 1280, endMs: 4020, intensity: 1 },
    { id: "sandbox-progress-2", kind: "nodeProgress", nodeId: "global-sandbox", startMs: 5080, endMs: 9120, intensity: 1 },
    { id: "control-pulse-1", kind: "nodePulse", nodeId: "control-plane", startMs: 520, endMs: 1220, intensity: 0.55 },
    { id: "control-pulse-2", kind: "nodePulse", nodeId: "control-plane", startMs: 2500, endMs: 3200, intensity: 0.55 },
    { id: "control-pulse-3", kind: "nodePulse", nodeId: "control-plane", startMs: 5000, endMs: 5700, intensity: 0.55 },
    { id: "control-pulse-4", kind: "nodePulse", nodeId: "control-plane", startMs: 7300, endMs: 8000, intensity: 0.55 },
    { id: "agent-1-presence-1", kind: "nodePresence", nodeId: "agent-1", startMs: 1380, endMs: 4200, intensity: 0.95 },
    { id: "agent-1-status-spawned-1", kind: "nodeStatus", nodeId: "agent-1", statusLabel: "Spawned", startMs: 1380, endMs: 1700, intensity: 1 },
    { id: "agent-1-status-running-1", kind: "nodeStatus", nodeId: "agent-1", statusLabel: "Running", startMs: 1700, endMs: 4200, intensity: 1 },
    { id: "agent-1-presence-2", kind: "nodePresence", nodeId: "agent-1", startMs: 8440, endMs: 10200, intensity: 0.95 },
    { id: "agent-1-status-spawned-2", kind: "nodeStatus", nodeId: "agent-1", statusLabel: "Spawned", startMs: 8440, endMs: 8720, intensity: 1 },
    { id: "agent-1-status-running-2", kind: "nodeStatus", nodeId: "agent-1", statusLabel: "Running", startMs: 8720, endMs: 10200, intensity: 1 },
    { id: "agent-2-presence-1", kind: "nodePresence", nodeId: "agent-2", startMs: 3140, endMs: 6180, intensity: 0.95 },
    { id: "agent-2-status-spawned-1", kind: "nodeStatus", nodeId: "agent-2", statusLabel: "Spawned", startMs: 3140, endMs: 3460, intensity: 1 },
    { id: "agent-2-status-running-1", kind: "nodeStatus", nodeId: "agent-2", statusLabel: "Running", startMs: 3460, endMs: 6180, intensity: 1 },
    { id: "agent-2-presence-2", kind: "nodePresence", nodeId: "agent-2", startMs: 7940, endMs: 10200, intensity: 0.95 },
    { id: "agent-2-status-spawned-2", kind: "nodeStatus", nodeId: "agent-2", statusLabel: "Spawned", startMs: 7940, endMs: 8220, intensity: 1 },
    { id: "agent-2-status-running-2", kind: "nodeStatus", nodeId: "agent-2", statusLabel: "Running", startMs: 8220, endMs: 10200, intensity: 1 },
    { id: "agent-3-presence", kind: "nodePresence", nodeId: "agent-3", startMs: 5620, endMs: 9020, intensity: 0.95 },
    { id: "agent-3-status-spawned", kind: "nodeStatus", nodeId: "agent-3", statusLabel: "Spawned", startMs: 5620, endMs: 5940, intensity: 1 },
    { id: "agent-3-status-running", kind: "nodeStatus", nodeId: "agent-3", statusLabel: "Running", startMs: 5940, endMs: 9020, intensity: 1 },
    { id: "agent-1-pulse-1", kind: "nodePulse", nodeId: "agent-1", startMs: 1520, endMs: 2140, intensity: 0.7 },
    { id: "agent-1-pulse-2", kind: "nodePulse", nodeId: "agent-1", startMs: 8580, endMs: 9200, intensity: 0.7 },
    { id: "agent-2-pulse-1", kind: "nodePulse", nodeId: "agent-2", startMs: 3480, endMs: 4100, intensity: 0.7 },
    { id: "agent-2-pulse-2", kind: "nodePulse", nodeId: "agent-2", startMs: 8280, endMs: 8900, intensity: 0.7 },
    { id: "agent-3-pulse", kind: "nodePulse", nodeId: "agent-3", startMs: 5960, endMs: 6580, intensity: 0.7 },
    { id: "edge-user-1", kind: "edgeEmphasis", edgeId: "user-to-control", startMs: 0, endMs: 820, intensity: 0.8 },
    { id: "edge-api-1", kind: "edgeEmphasis", edgeId: "api-to-control", startMs: 1960, endMs: 2780, intensity: 0.8 },
    { id: "edge-user-2", kind: "edgeEmphasis", edgeId: "user-to-control", startMs: 4460, endMs: 5280, intensity: 0.8 },
    { id: "edge-api-2", kind: "edgeEmphasis", edgeId: "api-to-control", startMs: 6760, endMs: 7580, intensity: 0.8 },
  ],
});
